name: k8s deployment on hpinc namespace

on:
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout hpinc repo main branch
      uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        sudo apt-get update -y
        sudo apt-get install kubectl -y

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Maven Clean and Install
      run: mvn clean install

    - name: Maven Test
      run: mvn test

    - name: Checkstyle Analysis
      run: mvn checkstyle:checkstyle

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t shiva .

    - name: Tag Docker image for ECR
      run: docker tag shiva:latest 619940455000.dkr.ecr.us-east-1.amazonaws.com/hpinc:latest

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: 619940455000.dkr.ecr.us-east-1.amazonaws.com
        region: us-east-1

    - name: Push Docker image to ECR
      run: docker push 619940455000.dkr.ecr.us-east-1.amazonaws.com/hpinc:latest
