name: k8s deployment on hpinc namespace

on:
  push:
    branches:
    - main

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout hpinc repo main branch
      uses: actions/checkout@v4

    - name: Install kubectl
      run: |
        sudo apt-get update -y
        sudo apt-get install kubectl -y

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Maven Clean and Install
      run: mvn clean install

    - name: Maven Test
      run: mvn test

    - name: Checkstyle Analysis
      run: mvn checkstyle:checkstyle




  build-and-push:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: vitr/actions-build-and-upload-to-ecs@master
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: hpinc
        region: us-east-1
        tags: latest,${{ github.sha }}
        create_repo: true
