name: k8s deployment on hpinc namespace
on:
  push:
    branches:
    - main
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: checkout hpinc repo main branch
      uses: actions/checkout@v4

    - name: install kubectl
      run: |
        sudo apt-get update -y
        sudo apt-get install kubectl -y

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Maven Clean and Install
      run: mvn clean install

    - name: Maven Test
      run: mvn test

    - name: Checkstyle Analysis
      run: mvn checkstyle:checkstyle

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
    - name: check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS
      run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set default.region ${{ secrets.AWS_REGION }}

    - name: Login to AWS ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 619940455000.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - run: docker build --tag my-image:v1 .
    - name: Push to ECR
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        image: my-image:v1


