name: hpinc flrxrig project
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: code checkout
      uses: actions/checkout@v4

    - name: mvn test
      run: mvn test

    - name: checkstyle test
      run: mvn checkstyle:checkstyle

    - name:

