name: k8s deployment on hpinc namespace
on:
  push:
    branches:
    - main
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: checkout hpinc repo main branch
      uses: actions/checkout@v4

    - name: install kubectl
      run: |
        sudo apt-get update -y
        sudo apt-get install kubectl -y

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Maven Clean and Install
      run: mvn clean install

